bin/pyenv-virtualenv-init
test/init.bats

When the current pyenv environment is not a virtualenv, this line
exits with a return code of 1. This is annoying for those of us
who report the last return code in our own PROMPT_COMMAND, so
ignore the output of `pyenv activate` if we're not currently using
a virtualenv.

Ignore failure of pyenv activate

---

README.md

Currently the link to venv points to the Japanese version of the Python documentation.
Change this link to the English version of the Python documentation.

Link to English venv documentation

---

bin/pyenv-virtualenv-init
test/init.bats

This makes it possible to use `eval "$(pyenv virtualenv-init -)"` from a
function.

Use `typeset -g` with `precmd_functions`

---

bin/pyenv-sh-activate
bin/pyenv-virtualenv-init
test/activate.bats
test/init.bats

This fixes displaying the note, in case "init" has been run manually
and/or the init is not in the expected place.
It removes the unnecessary calls to "grep".
pyenv-virtualenv-init will look at `$PYENV_SHELL` now, too.
Tests have been adjusted/fixed.

activate: do not display note if initialized already

---

bin/pyenv-virtualenv-init
test/init.bats
test/test_helper.bash

- fixes `ps` command to lookup parent process
- adds `assert_output_contains_not` test helper
Ref: https://github.com/yyuu/pyenv/issues/373

init: fix shell detection when invoked from a script

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
bin/pyenv-virtualenv-init
bin/pyenv-virtualenv-prefix
bin/pyenv-virtualenvs
test/activate.bats
test/conda-activate.bats
test/conda-deactivate.bats
test/conda-virtualenv-prefix.bats
test/deactivate.bats
test/init.bats
test/test_helper.bash
test/virtualenvs.bats

With this patch, we can just simply specify a conda environment as `miniconda3-3.9.1/envs/myenv`.
```sh
% pyenv versions
system
2.7.10
miniconda3-3.9.1
% pyenv shell miniconda3-3.9.1
discarding /home/yyuu/.pyenv/versions/miniconda3-3.9.1/bin from PATH
prepending /home/yyuu/.pyenv/versions/miniconda3-3.9.1/bin to PATH
(root)% conda env list
#
myenv                    /home/yyuu/.pyenv/versions/miniconda3-3.9.1/envs/myenv
root                  *  /home/yyuu/.pyenv/versions/miniconda3-3.9.1
(root)% pyenv virtualenvs
* miniconda3-3.9.1 (created from /home/yyuu/.pyenv/versions/miniconda3-3.9.1)
miniconda3-3.9.1/envs/myenv (created from /home/yyuu/.pyenv/versions/miniconda3-3.9.1)
(root)% pyenv activate myenv
discarding /home/yyuu/.pyenv/versions/miniconda3-3.9.1/bin from PATH
prepending …
```

Manage Anaconda/Miniconda environment as a pyenv version

---

bin/pyenv-virtualenv-init
test/init.bats

In fish, the pyenv was not automatically being deactivated on directory change. Turns out that, because of the quotes, it was comparing the command string instead of the command output, which was never true. Removing the quotes resolved the issue.

pyenv-virtualenv-init fix for fish

---

bin/pyenv-virtualenv-init
test/init.bats

It is not possible to read "exit status" of executed command by using for example `echo $?`. The problem is with the function `_pyenv_virtualenv_hook` which always returns 0. Saving and returning previous exit code should help.

Passing return value from executed command.

---

bin/pyenv-virtualenv-init
test/init.bats

This makes sure that $VIRTUAL_ENV is handled already in other precmd
functions, especially your prompt.
The hack/workaround to achieve this yourself:
precmd_functions=(_pyenv_virtualenv_hook $precmd_functions)
eval "$(pyenv virtualenv-init -)"

init: zsh: prepend hook to precmd_functions

---

bin/pyenv-virtualenv
test/hooks.bats
test/pip.bats
test/python.bats
test/pyvenv.bats
test/virtualenv.bats

This changes the installation path of virtualenv as similar as Anaconda/Miniconda. This would be reasonable since every virtualenvs are actually depending on its source version, and they cannot work alone.
This is a kind of breaking change. To mitigate the migration cost, I prepared a symlink of `COMPAT_VIRTUALENV_PATH` for backward compatibility.

Create virtualenv inside `envs` directory as similar as Anaconda

---

bin/pyenv-virtualenv-delete
etc/pyenv.d/rehash/envs.bash
etc/pyenv.d/uninstall/envs.bash
test/delete.bats

This is mainly for Anaconda/Miniconda, to improve the support for virtual environments created in `envs` directory. (e.g. `~/.pyenv/versions/miniconda3-3.16.0/envs/foo`) With this, `pyenv rehash` will create _shims_ for executables installed in virtual environments in `envs`.

Support uninstall and rehash of virtual environments created in `envs`

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
bin/pyenv-virtualenv-init
test/activate.bats
test/conda-activate.bats
test/conda-deactivate.bats
test/deactivate.bats
test/init.bats

If first version is a virtualenv, this will activate it even if there are multiple versions. It will not activate if there are multiple virtualenvs in the versions. I believe this fixes #105.
This also includes some of backward incompatible changes.
1. `PYENV_ACTIVATE` will never persist
1. Remove support for short-form name of `conda` style environments.
* `env PYENV_VERSION=miniconda3-3.16.0 pyenv activate foo #==> activate miniconda3-3.16.0/envs/foo`

Change `activate` behavior on multiple versions

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
bin/pyenv-virtualenv
test/activate.bats
test/conda-activate.bats
test/conda-deactivate.bats
test/deactivate.bats
test/version.bats

This will change existing behaviour a little. Though removing error prone feature would be beneficial than corner cases.
If a user wants to activate/deactivate manually, I'd recommend s?he to remove `eval "$(pyenv virtualenv-init -)"` from his/her shell configuration.
@blueyed can you give a look on this?

Remove `PYENV_DEACTIVATE`

---

README.md
bin/pyenv-virtualenv
test/conda-activate.bats
test/conda-deactivate.bats
test/conda-prefix.bats
test/conda.bats
test/hooks.bats
test/pip.bats
test/python.bats
test/pyvenv.bats
test/test_helper.bash
test/version.bats
test/virtualenv.bats

With Anaconda/Miniconda version, `pyenv virtualenv` will automatically use `conda create` implicitly.

Use `conda create` to create virtual environment if `conda` is available

---

README.md

As announced in #135, I added an improvement to the README.
It clarifies the usage of the auto-activation functionality which I couldn't make work on my own. Searching through old, closed issues, I discovered #52, which described the same problem and in fact helped me figure out what I was missing. I thought it'd be a good idea to add this to the README to save others the trouble/time!

Clarification of auto-activation/deactivation feature

---

README.md

Issue described in #157. I changed the example of `pyenv virtualenvs`, listings twice the two virtualenvs created in the previous sections. 
Before this change, the output of `pyenv virtualenvs` listed only one entry per virtualenv. Furthermore, there was listed a virtualenv not previously created.

`pyenv virtualenvs` lists two entries for each virtualenv

---

bin/pyenv-virtualenv-init
test/init.bats

* https://github.com/yyuu/pyenv/pull/615
* https://github.com/fish-shell/fish-shell/issues/310

Use `source` in favor of `.` (fixes #175)

---

README.md

When I came back to this after a few months - despite setting it up properly previously - I was a bit confused since I'm so used to setting an actual Python version in `.python-version` files. Explain exactly how the file should look.

Be more explicit about `.python-version` file

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
test/conda-activate.bats
test/conda-deactivate.bats

The `CONDA_PREFIX` environment variable is used in some activate/deactivate scripts. If it is not set they do not work correctly. One example is the [gdal package](https://github.com/conda-forge/libgdal-feedstock/blob/master/recipe/scripts/activate.sh). 
The `CONDA_PREFIX` variable is normally set in [activate](https://github.com/conda/conda/blob/301133cb8c804730c218ad8e47f116a8b1af51fc/conda/activate.py#L241) which is not used in pyenv.

Set CONDA_PREFIX to make is useable in conda activate/deactivate scripts

---

bin/pyenv-virtualenv
test/pyvenv.bats
test/virtualenv.bats

`virtualenv` will generate `pydoc` as a shell alias, not as an executable. Because pyenv's relying on shim script, there should be some executable to work it properly.
(fixes #197, pyenv/pyenv#963)

Generate `pydoc` executable after creating new virtualenv

---

bin/pyenv-sh-activate

Conda 4.4.4 (https://github.com/conda/conda/releases/tag/4.4.0) made some changes on how to set up conda in the shell. This commit addresses these.
This fixes some of the discussion in #178.
Note that this requires conda/conda#7004 to be merged first (at least for those of us who use fish).

Source conda 4.4.4 shell files

---

bin/pyenv-virtualenv

cf. pyenv/pyenv-installer#70 https://github.com/pyenv/pyenv/pull/1124

Unset `PIP_VERSION` before invoking `get-pip.py` as a workaround for `invalid truth value` error

---

bin/pyenv-virtualenv

Manage `GET_PIP_URL` value at single place for readability. Similar changes as https://github.com/pyenv/pyenv/pull/1128

Refactoring around `GET_PIP_URL`

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
bin/pyenv-virtualenv
bin/pyenv-virtualenv-prefix
bin/pyenv-virtualenvs
etc/pyenv.d/which/conda.bash
libexec/pyenv-virtualenv-realpath

pyenv-virtualenv had issues listing conda environments, activating conda environments, and cleaning up `pyenv virtualenv` runs on error.
The issue is primarily explained in #178: `conda` and `activate` files no longer exist under derived conda environment `bin` directories, so `pyenv-virtualenv` can't use them to detect conda.
To resolve this, I add criteria to detect a `conda-meta` subdirectory.
Obtaining `VIRTUALENV_PREFIX_PATH` uses an implementation of `realpath` that would normalize paths across multiple scripts (though this might also be achieved with `cd` in a subshell).
(Moreover, I'm puzzled that substitutes for `readlink` and related commands are redefined throughout several scripts instead of defined in a single file for inclusion via `source`ing. Is there a reason for this?)
A …

Fix: support newer conda

---

README.md
bin/pyenv-virtualenv-init

Otherwise, there's no effect for non-login interactive shells
Closes #383

~/.*rc should be modified instead of ~/.*profile

---

bin/pyenv-virtualenvs

Fixes #394 
**After this small fix:**
1. `$ pyenv virtualenv 3.8.10 .my_virtualenv`
2. `$ pyenv virtualenvs --skip-aliases`
`3.8.10/envs/.my_virtualenv (created from /opt/app-root/src/.pyenv/versions/3.8.10)`

Fixes #394 - update pyenv virtualenvs to list virtualenvs start with dot prefixes

---

README.md

The text included info on Pyenv startup which is now outdated and incorrect.
Closes https://github.com/pyenv/pyenv/issues/1947, https://github.com/pyenv/pyenv-virtualenv/issues/387

Fix installation steps to allow for Pyenv 2

---

bin/pyenv-virtualenv

This PR updates the get-pip.py URL for Python 2.6 and adds the URL for Python 2.7.

Fix get-pip.py URLs for older versions of Python

---

bin/pyenv-virtualenv-delete

There is no example input like (y/N) or something so I often get confused if I just have to press enter or type y(or Y, yes, YES whatever)
So to be clear I added some help text just like other scripts
ex. [pyenv-install](https://github.com/pyenv/pyenv/blob/8b60418361e29d30fbe7ee3133e57f4d351464da/plugins/python-build/bin/pyenv-install#L160)

Add (y/N) prompt help text

---

bin/pyenv-sh-activate

Before:
```shellsession
$ hyperfine -i "pyenv sh-activate --quiet"
Benchmark #1: pyenv sh-activate --quiet
Time (mean ± σ):      49.1 ms ±   3.0 ms    [User: 40.7 ms, System: 10.7 ms]
Range (min … max):    45.4 ms …  59.0 ms    53 runs
```
After:
```shellsession
$ hyperfine -i "pyenv sh-activate --quiet"
Benchmark #1: pyenv sh-activate --quiet
Time (mean ± σ):      39.5 ms ±   1.4 ms    [User: 31.4 ms, System: 9.7 ms]
Range (min … max):    36.4 ms …  44.8 ms    70 runs
```

perf(sh-activate): avoid a pyenv-version-name call

---

bin/pyenv-sh-activate
test/activate.bats
test/conda-activate.bats
test/conda-deactivate.bats
test/deactivate.bats

This fixes the case of `bash: PS1: unbound variable` when `PYENV_VIRTUALENV_DISABLE_PROMPT` isn't set.
This should have been part of #423, sorry for that. I also fixed the tests related to virtualenv activation/deactivation which were failing due to my changes.

Fix another unbound variable error

---

etc/pyenv.d/uninstall/envs.bash

Found only the link is uninstalled by `pyenv unisntall` but not the original env. It turns out that the bug is related with pyenv/pyenv#2432.
Here's a fix that refactor the code to register itself as a hook explicitly and let the hook called by `pyenv uninstall` for multiple versions.

Upgrade uninstall hook after pyenv/pyenv#2432

---

bin/pyenv-virtualenv-delete

When `pyenv virtualenv-delete -f non-existent-virtualenv` is run then an error message is displayed and the return code is 1
This is contrary to the behavior described by `pyenv virtualenv-delete --help`:
```
Usage: pyenv virtualenv-delete [-f|--force] <virtualenv>
-f  Attempt to remove the specified virtualenv without prompting
for confirmation. If the virtualenv does not exist, do not
display an error message.
See `pyenv virtualenvs` for a complete list of installed versions.
```
Specifically for the force flag: `If the virtualenv does not exist, do not display an error message.`
This PR addresses this by checking that the force flag is not set before continuing with standard behavior (displaying the error message and returning the non-zero code).

Stop delete force failing when virtualenv does not exist

---

bin/pyenv-virtualenv-init
test/init.bats

Fixes for shells runnin in `set -u` /  `set -o nounset` mode

set -u fixes

---

etc/pyenv.d/uninstall/envs.bash

This would fix #320, since returning control to `pyenv-uninstall` would allow the rest of the `before_uninstall` and `after_install` hooks to run.
From my understanding, the `exec` would pass control to the other script and never return it, so it would never hit the `exit`.. and if it did, there's no real need to since they are in mutually exclusive `if` statements. However, I might be misunderstanding something here, or there might have been a reason it was done like that, so it's quite possible there's a problem with this solution that I'm not aware of.
One problem I noticed was the error when returning control to `pyenv-uninstall`. Setting `FORCE=t` avoids this error, although I'm not sure what exactly that does so I'm not sure if there's any issues with that.

Return control to pyenv-uninstall in uninstall/envs.bash

---

bin/pyenv-virtualenv-prefix
bin/pyenv-virtualenvs

Just using paths relative to `${BASH_SOURCE}` fails if the scripts are
symlinked to a location, as that variable reports the path at which
the script is invoked, not where it actually resides.  This commit
implements a simple version of the realpath functionality in order to
determine the path to the more comprehensive realpath script
This should resolve my issue #307

Use realpath of scripts to determine relative locations

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
test/activate.bats
test/conda-activate.bats
test/conda-deactivate.bats
test/deactivate.bats
test/hooks.bats

`activate`/`deactivate` hooks have been discussed several times but I haven't seen a PR, so... here's one :)
There are two test failures in `test/activate` and `test/deactivate` that I _think_ are just me not fully understanding the stub system, do you mind taking a look and pointing me in the right direction? Thanks so much!
---
Past discussions:
1. Closes https://github.com/pyenv/pyenv-virtualenv/issues/428
2. https://github.com/pyenv/pyenv-virtualenv/issues/55
3.  https://github.com/pyenv/pyenv/issues/2337

Add activate/deactivate hooks

---

bin/pyenv-virtualenv
test/python.bats

Added a more helpful error message for when you're trying to create a virtual environment with python version which is not installed. As a user i keep running into this: i want to make a particular vent but i don't have the python and i have 
If I try to install a non-existent python with peen I get something like that:
```
python-build: definition not found: 3.9.99
See all available versions with `pyenv install --list'.
If the version you need is missing, try upgrading pyenv.
```
with a possibility of getting even more help by listing all the candidates which contain the version passed and trying to be helpful as to how to upgrade pyenv (implementation form 2.3.17 ca be seen [here](https://github.com/pyenv/pyenv/blob/9a4f9c2511f39701cb8e3af1e6809be28210c3b9/plugins/python-build/bin/pyenv- …

More helpful error message

---

bin/pyenv-virtualenv
test/virtualenv.bats

Closes https://github.com/pyenv/pyenv-virtualenv/issues/459

Link python*-config into VE

---

bin/pyenv-virtualenv

fixes #381 -- in the event that someone sets the `PIP_VERSION` environment variable, pyenv-virtualenv plugin will fail because a `colorize` utility is not available, this PR adds the `colorize` helper from `python-build`

fix: add `colorize` helper

---

bin/pyenv-virtualenv

The latest release so far (Dec 2023) is 1.2.2, but the version reported is still 1.2.1:
https://github.com/pyenv/pyenv-virtualenv/releases/tag/v1.2.2
Fix #464 #465 
Related #449

Bump pyenv-virtualenv reporting version to match release

---

bin/pyenv-sh-activate
bin/pyenv-sh-deactivate
test/activate.bats
test/conda-activate.bats
test/conda-deactivate.bats
test/deactivate.bats

Hi! I use pyenv every day, and it is truly a lifesaver. The only thing that bugs me is the fact that activating a virtual environment does not change the prompt in fish. I have introduced this fix which caches the old prompt and displays a new one with the appropriate prefix. 
```sh
> pyenv virtualenv 3.12 test 
> pyenv activate test
(test) > pyenv virtualenv 3.12 test1
(test) > pyenv activate test1
(test1) > pyenv deactivate
> 
```
> Note: old prompt is cached in `_pyenv_old_prompt`. It is automatically erased during deactivation and accounted for during activation.
I hope this is useful to everyone else! Thanks for your consideration.

Fix fish prompt

---

README.md

Github has a button next to code blocks that lets you copy that block to your clipboard. It took me too long to realize that the install commands I copied included a `$` character, based on the formatting in the code blocks here.
This PR removes those dollar signs from single commands that would be useful to copy, to eliminate the confusion I had.
I left the dollar signs in the blocks that show both commands and their output.

README: removing dollar signs from commands that are meant to be copied

---

.github/workflows/tests.yml
bin/pyenv-virtualenv
test/virtualenv.bats

Closes https://github.com/orgs/pyenv/discussions/3023

Reflect pyenv-latest switch change in 2.4.8

---

README.md
bin/pyenv-sh-activate
test/activate.bats
test/conda-activate.bats
test/hooks.bats

Grants users the option of providing a custom prompt configuration for `pyenv-virtualenv` by setting an environment variable (preferably, at shell initialization).
I've been using `pyenv` for years now, and have used this modification personally for most of that time. For those users that prefer to customize their shell prompts for clarity or vanity, this can make `pyenv-virtualenv` a better experience.
The default prompt looks like:
```shell
~ $ eval "$(pyenv init -)"
~ $ eval "$(pyenv virtualenv-init -)"
~ $ pyenv activate my-venv
(my-venv) ~ $
```
With my proposed changes:
```shell
~ $ export PYENV_VIRTUALENV_PROMPT='venv:{venv}'
~ $ eval "$(pyenv init -)"
~ $ eval "$(pyenv virtualenv-init -)"
~ $ pyenv activate my-venv
venv:my-venv ~ $
```

Add prompt customization

---

bin/pyenv-virtualenv
test/conda.bats
test/deactivate.bats
test/test_helper.bash

Fixes https://github.com/pyenv/pyenv-virtualenv/issues/491

Fix pyenv-virtualenv using a different Python version in a conda environment

---

bin/pyenv-activate
bin/pyenv-deactivate

Closes https://github.com/pyenv/pyenv-virtualenv/issues/401
Closes https://github.com/pyenv/pyenv-virtualenv/issues/389

Fix confusing activate/deactivate error messages when Pyenv is not installed as a shell function

---

README.md

Adds a brief note to the installation section for WSL users, recommending the use of:
```sh
git config --global core.autocrlf input
```
This prevents common CRLF-related issues (e.g., /usr/bin/env: ‘bash\r’: No such file or directory) when using pyenv-virtualenv under WSL.
The note appears right before the manual git clone instructions, where it’s most relevant for users following the README directly.
This follows up on the discussion in #509

docs: add WSL note about core.autocrlf to prevent CRLF issues

---

README.md

I believe the original page anchor was removed during a content update in the pyenv repo. This caused some inconvenience when I was setting up the pyenv-virtual plugin. I’ve replaced the link with the closest matching anchor, but I’m open to adjusting the link title to maintain consistency. 😃

docs: fix the link to Pyenv shell setup steps
